think its working now

diff --git a/bin/tmper b/bin/tmper
--- a/bin/tmper
+++ b/bin/tmper
@@ -10,25 +10,34 @@ BLUE='\033[0;34m'
 PURPLE='\033[0;35m'
 YELLOW='\033[1;33m'
 
-if ! hash cpath 2>/dev/null; then
-  >&2 printf "%b- cpath required, installing globally... -%b" "$CYAN" "$NC"
-  npm install -g cpath
+if ! hash rimraf 2>/dev/null; then
+  >&2 printf "%b- rimraf required, installing globally... -%b" "$CYAN" "$NC"
+  npm install -g rimraf
 fi
 
-delete_flag=false
+if ! hash mkdirp 2>/dev/null; then
+  >&2 printf "%b- mkdirp required, installing globally... -%b" "$CYAN" "$NC"
+  npm install -g mkdirp
+fi
 
-usage_short="${BLUE}usage: tmper [-d]"
-usage_long="$usage_short\n-d: safe delete temporary directory at path (default: $delete_junc)"
+TMP_ROOT="${TMP-"$TEMP"}"
+DELETE_FLAG=false
+NAME_LENGTH=5
+
+
+usage_short="${BLUE}usage: tmper [-d /temp/dir]"
+usage_long="$usage_short\n-d: safe delete temporary directory at path (default: $DELETE_FLAG)"
 
 usage_short="$usage_short\nuse -h to get supported command information.${NC}"
 
-options=":dh"
+options=":d:h"
 shopt -u nocasematch
 OPTIND=1
 while getopts "$options" opt ; do
     case "$opt" in
     d )
-      delete_flag=true
+      DELETE_FLAG=true
+      DIR_ROOT="$OPTARG"
       ;;
    h )
       >&2 printf -- "%b\n" "$usage_long"
@@ -53,27 +62,24 @@ done
 shift $((OPTIND-1))
 
 generate_name() {
-  < /dev/urandom tr -dc a-z | head -c${1:-32};echo;
+  printf -- "%s" "$(</dev/urandom tr -dc a-z | head -c${1:-32})"
 }
 
-win_dir_path="$(cpath -w "$dir_path")"
-
-if [ "$delete_junc" = true ] ; then
-  cmd //c rmdir "$win_dir_path" &>/dev/null
-  exit 0
+if [ "$DELETE_FLAG" = true ]; then
+  if [[ $DIR_ROOT == "$TMP_ROOT"* ]]; then
+    rimraf "$DIR_ROOT"
+    exit 0
+  fi
+  >&2 printf -- "%b- %s is not a part of temp directory, will not delete... -%b" "$RED" "$DIR_ROOT" "$NC"
+  exit 1
 fi
 
-# Perform junction, loop in case random returns the same name twice
-junc_name="$(generate_name "$name_length")"
-junc_path="$junc_root/$junc_name"
-while [ -e "$junc_path" ] ; do
-  junc_name="$(generate_name "$name_length")"
-  junc_path="$junc_root/$junc_name"
+tmp_name="$(generate_name "$NAME_LENGTH")"
+tmp_dir="$TMP_ROOT/$tmp_name"
+while [ -e "$tmp_dir" ] ; do
+  tmp_name="$(generate_name "$NAME_LENGTH")"
+  tmp_dir="$TMP_ROOT/$tmp_name"
 done
 
-win_junc_path="$(cpath -w "$junc_path")"
-
-mkdir -p "$junc_root" &>/dev/null
-cmd //c mklink //J "$win_junc_path" "$win_dir_path" &>/dev/null
-
-printf "%s" "$junc_path"
+mkdirp "$tmp_dir" &>/dev/null
+printf -- "%s" "$tmp_dir"
